### PR TITLE
Update DNS for email provider change

### PR DESCRIPTION
**Pull request by ghost**
This should update all of the necessary DNS records to make our switch to FastMail for handling mail traffic.

### CODE REVIEW

**Comment by parkr** [comment]
Thank you! Can you point me for the documentation for these changes? Never used fastmail before :)

**Comment by oe** [comment]
@parkr Sure, here's the standard DNS records that Fastmail sets. I've used a subset of them, namely the one I think would make sense for us: https://www.fastmail.com/help/receive/domains-advanced.html?u=66a9409d#dnslist

**Comment by oe** [comment]
Can this be merged @parkr?

**Comment by parkr** [comment]
```text
********************************************************************************
* jekyllrb.com.
********************************************************************************
* cloudflare (CloudflareProvider)
*   Update
*     <ARecord A 1, talk.jekyllrb.com., ['216.218.240.80']> ->
*     <ARecord A 600, talk.jekyllrb.com., ['216.218.240.80']> (config)
*   Update
*     <TxtRecord TXT 600, jekyllrb.com., ['v=spf1 include:mailgun.org include:_hostedspf.discourse.org ~all']> ->
*     <TxtRecord TXT 600, jekyllrb.com., ['v=spf1 include:spf.messagingengine.com include:mailgun.org include:_hostedspf.discourse.org ~all']> (config)
*   Update
*     <MxRecord MX 600, jekyllrb.com., [''10 mxa.mailgun.org.'', ''20 mxb.mailgun.org.'']> ->
*     <MxRecord MX 600, jekyllrb.com., [''10 in1-smtp.messagingengine.com.'', ''20 in2-smtp.messagingengine.com.'']> (config)
*   Delete <CnameRecord CNAME 600, email.talk.jekyllrb.com., mailgun.org.>
*   Delete <CnameRecord CNAME 600, email.jekyllrb.com., mailgun.org.>
*   Create <ARecord A 600, mail.jekyllrb.com., ['66.111.4.147', '66.111.4.148']> (config)
*   Create <TxtRecord TXT 600, fm3._domainkey.jekyllrb.com., ['fm3.jekyllrb.com.dkim.fmhosted.com']> (config)
*   Create <TxtRecord TXT 600, fm2._domainkey.jekyllrb.com., ['fm2.jekyllrb.com.dkim.fmhosted.com']> (config)
*   Create <TxtRecord TXT 600, fm1._domainkey.jekyllrb.com., ['fm1.jekyllrb.com.dkim.fmhosted.com']> (config)
*   Create <TxtRecord TXT 600, mesmtp._domainkey.jekyllrb.com., ['mesmtp.jekyllrb.com.dkim.fmhosted.com']> (config)
*   Summary: Creates=5, Updates=3, Deletes=2, Existing Records=15
********************************************************************************


2018-10-12T11:47:45  [140735677363072] INFO  CloudflareProvider[cloudflare] apply: making changes
2018-10-12T11:47:48  [140735677363072] INFO  Manager sync:   10 total changes
```

**Pull request merged**
